### ISSUE TITLE
讲一讲今天 B 站玩 CTF 的经历 - Ela の 个人博客

### ISSUE THREAD

**Issue by ElaBosak233** [ElaBosak233/ElaBosak233.github.io#7]
https://ela.ac.cn/2020/10/24/%E8%AE%B2%E4%B8%80%E8%AE%B2%E4%BB%8A%E5%A4%A9B%E7%AB%99%E7%8E%A9CTF%E7%9A%84%E7%BB%8F%E5%8E%86/#more

**Comment by ERHECY** [comment]
做到第六题就不想做了

**Comment by ElaBosak233** [comment]
> @ERHECY
> 做到第六题就不想做了

同感，第六题就是分水岭，那些做出第六题的真的神 = =
